#!/bin/bash
path=/var/log/auth.log
if [ ! -f $path];then
  echo "log file doesnt exist here"
  exit 1
fi
echo "failed login SSH attempts"
resultat=$(grep "Failed password" "$LOG_FILE"| grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | sort | uniq -c | sort -rn)